image: node:8

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - npm update

# You specify the stages. Those are the steps that GitLab will go through
# Order matters.
stages:
  - test

Test:
  stage: test
  tags:
    - node
  script:
    - npm run test
