variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - install
  - test

install_docker:
  stage: install
  image: docker:stable
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose 
    - docker info
    - docker-compose --version
    - docker volume create --name=pgdata
  script:
    - docker-compose -f docker/docker-compose.yml build
  only:
    - master

test:
  stage: test
  image: docker:stable
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose 
    - docker info
    - docker-compose --version
    - docker volume create --name=pgdata
    - apk --update add nodejs nodejs-npm
    - cd ./app
    - npm install
    - cd ..
  script:
    - docker-compose run
    - cd app
    - npm test
    . cd ..
  only:
    - master
  dependencies:
    - install_docker
