version: "3.5"

services:
  app:
    container_name: app
    build: "./app"
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"

    environment:
      DATABASE_URL: postgres://dbuser:dbpassword@db:5432/articlesdb
      #- PGHOST=db
      #- PGPORT=5432
      #- PGUSER=dbuser
      #- PGPASSWORD=dbpassword
      #- PGDATABASE=articlesdb
      #- NODE_ENV=development

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=articlesdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - PGDATA=/tmp
    ports:
      - "5432:5432"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
