apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./k8s
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  ports:
  - name: "7070"
    port: 7070
    targetPort: 8080
  selector:
    io.kompose.service: cadvisor
  type: LoadBalancer
status:
  loadBalancer: {}
