module.exports = {
  article: {
    1: {
      id: 1,
      title: "Example",
      authors: "Federico Bottoni, Nassim Habbash",
      text:
        "Vivamus efficitur sollicitudin ex, quis dapibus dui bibendum vel. Integer bibendum metus iaculis mattis fermentum. Fusce ut tortor odio. Pellentesque nec justo ac ligula pulvinar ultricies. Sed quis quam ac nulla dictum mollis eu id ante. Nullam maximus magna eu convallis blandit. Curabitur tristique scelerisque quam, et iaculis quam ultricies vitae. In neque lacus, volutpat id luctus id, vulputate et ipsum. Proin faucibus, lorem quis luctus tincidunt, massa dolor placerat dolor, sit amet efficitur purus orci quis turpis. Proin fringilla dui quis leo imperdiet, vel laoreet eros volutpat. Mauris in leo ut purus condimentum ullamcorper vitae nec purus. Nunc ut dictum risus. Vestibulum at nisi pellentesque leo cursus malesuada. Nunc in massa diam.\n Etiam cursus, lacus ut aliquam fermentum, justo elit pharetra nisi, eget semper leo ex ut metus. Vivamus arcu orci, varius et pretium vitae, fermentum vitae nisi. Duis in facilisis massa. Quisque fermentum risus rhoncus nisi aliquam tincidunt. Praesent sed pellentesque eros. In tincidunt massa nisi, ut consequat neque feugiat sed. Phasellus varius odio in condimentum accumsan. Vestibulum sit amet malesuada mauris, et pellentesque eros. Etiam sed fermentum ipsum. Duis cursus molestie ligula, hendrerit fermentum sem tristique non. Phasellus viverra sit amet velit ut consequat. Nullam elementum, risus tempus mattis maximus, dui nunc vehicula magna, in faucibus lectus velit in massa. Vivamus mollis mauris vel ipsum aliquam, ac ultrices felis pellentesque.\n Nullam dapibus aliquet dapibus. Pellentesque maximus felis ac neque pretium consectetur. Quisque tincidunt nec magna sit amet convallis. Duis quis placerat mauris, non bibendum purus. Cras vel mattis libero. Donec in elit felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque eu porttitor justo, vel pulvinar dolor. Donec sed tempus enim. Praesent leo ligula, sollicitudin ac nisi a, rhoncus tempor erat. Nam malesuada eros non purus malesuada lacinia. Ut ac aliquet nisi. Etiam dui urna, mattis quis interdum sed, bibendum quis risus. Sed fermentum consectetur tellus, quis tristique metus euismod ac. Mauris pharetra eget massa in suscipit. Etiam posuere, quam in lacinia convallis, quam sem tempor elit, ut commodo ligula lorem eget sem."
    },
    2: {
      id: 2,
      title: "Test",
      authors: "Federico Bottoni, Nassim Habbash",
      text:
        "Vivamus efficitur sollicitudin ex, quis dapibus dui bibendum vel. Integer bibendum metus iaculis mattis fermentum. Fusce ut tortor odio. Pellentesque nec justo ac ligula pulvinar ultricies. Sed quis quam ac nulla dictum mollis eu id ante. Nullam maximus magna eu convallis blandit. Curabitur tristique scelerisque quam, et iaculis quam ultricies vitae. In neque lacus, volutpat id luctus id, vulputate et ipsum. Proin faucibus, lorem quis luctus tincidunt, massa dolor placerat dolor, sit amet efficitur purus orci quis turpis. Proin fringilla dui quis leo imperdiet, vel laoreet eros volutpat. Mauris in leo ut purus condimentum ullamcorper vitae nec purus. Nunc ut dictum risus. Vestibulum at nisi pellentesque leo cursus malesuada. Nunc in massa diam.\n Etiam cursus, lacus ut aliquam fermentum, justo elit pharetra nisi, eget semper leo ex ut metus. Vivamus arcu orci, varius et pretium vitae, fermentum vitae nisi. Duis in facilisis massa. Quisque fermentum risus rhoncus nisi aliquam tincidunt. Praesent sed pellentesque eros. In tincidunt massa nisi, ut consequat neque feugiat sed. Phasellus varius odio in condimentum accumsan. Vestibulum sit amet malesuada mauris, et pellentesque eros. Etiam sed fermentum ipsum. Duis cursus molestie ligula, hendrerit fermentum sem tristique non. Phasellus viverra sit amet velit ut consequat. Nullam elementum, risus tempus mattis maximus, dui nunc vehicula magna, in faucibus lectus velit in massa. Vivamus mollis mauris vel ipsum aliquam, ac ultrices felis pellentesque.\n Nullam dapibus aliquet dapibus. Pellentesque maximus felis ac neque pretium consectetur. Quisque tincidunt nec magna sit amet convallis. Duis quis placerat mauris, non bibendum purus. Cras vel mattis libero. Donec in elit felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque eu porttitor justo, vel pulvinar dolor. Donec sed tempus enim. Praesent leo ligula, sollicitudin ac nisi a, rhoncus tempor erat. Nam malesuada eros non purus malesuada lacinia. Ut ac aliquet nisi. Etiam dui urna, mattis quis interdum sed, bibendum quis risus. Sed fermentum consectetur tellus, quis tristique metus euismod ac. Mauris pharetra eget massa in suscipit. Etiam posuere, quam in lacinia convallis, quam sem tempor elit, ut commodo ligula lorem eget sem."
    },
    3: {
      id: 3,
      title: "Mock",
      authors: "Federico Bottoni, Nassim Habbash",
      text:
        "Vivamus efficitur sollicitudin ex, quis dapibus dui bibendum vel. Integer bibendum metus iaculis mattis fermentum. Fusce ut tortor odio. Pellentesque nec justo ac ligula pulvinar ultricies. Sed quis quam ac nulla dictum mollis eu id ante. Nullam maximus magna eu convallis blandit. Curabitur tristique scelerisque quam, et iaculis quam ultricies vitae. In neque lacus, volutpat id luctus id, vulputate et ipsum. Proin faucibus, lorem quis luctus tincidunt, massa dolor placerat dolor, sit amet efficitur purus orci quis turpis. Proin fringilla dui quis leo imperdiet, vel laoreet eros volutpat. Mauris in leo ut purus condimentum ullamcorper vitae nec purus. Nunc ut dictum risus. Vestibulum at nisi pellentesque leo cursus malesuada. Nunc in massa diam.\n Etiam cursus, lacus ut aliquam fermentum, justo elit pharetra nisi, eget semper leo ex ut metus. Vivamus arcu orci, varius et pretium vitae, fermentum vitae nisi. Duis in facilisis massa. Quisque fermentum risus rhoncus nisi aliquam tincidunt. Praesent sed pellentesque eros. In tincidunt massa nisi, ut consequat neque feugiat sed. Phasellus varius odio in condimentum accumsan. Vestibulum sit amet malesuada mauris, et pellentesque eros. Etiam sed fermentum ipsum. Duis cursus molestie ligula, hendrerit fermentum sem tristique non. Phasellus viverra sit amet velit ut consequat. Nullam elementum, risus tempus mattis maximus, dui nunc vehicula magna, in faucibus lectus velit in massa. Vivamus mollis mauris vel ipsum aliquam, ac ultrices felis pellentesque.\n Nullam dapibus aliquet dapibus. Pellentesque maximus felis ac neque pretium consectetur. Quisque tincidunt nec magna sit amet convallis. Duis quis placerat mauris, non bibendum purus. Cras vel mattis libero. Donec in elit felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque eu porttitor justo, vel pulvinar dolor. Donec sed tempus enim. Praesent leo ligula, sollicitudin ac nisi a, rhoncus tempor erat. Nam malesuada eros non purus malesuada lacinia. Ut ac aliquet nisi. Etiam dui urna, mattis quis interdum sed, bibendum quis risus. Sed fermentum consectetur tellus, quis tristique metus euismod ac. Mauris pharetra eget massa in suscipit. Etiam posuere, quam in lacinia convallis, quam sem tempor elit, ut commodo ligula lorem eget sem."
    },
    4: {
      id: 4,
      title: "Example4",
      authors: "Federico Bottoni, Nassim Habbash",
      text:
        "Vivamus efficitur sollicitudin ex, quis dapibus dui bibendum vel. Integer bibendum metus iaculis mattis fermentum. Fusce ut tortor odio. Pellentesque nec justo ac ligula pulvinar ultricies. Sed quis quam ac nulla dictum mollis eu id ante. Nullam maximus magna eu convallis blandit. Curabitur tristique scelerisque quam, et iaculis quam ultricies vitae. In neque lacus, volutpat id luctus id, vulputate et ipsum. Proin faucibus, lorem quis luctus tincidunt, massa dolor placerat dolor, sit amet efficitur purus orci quis turpis. Proin fringilla dui quis leo imperdiet, vel laoreet eros volutpat. Mauris in leo ut purus condimentum ullamcorper vitae nec purus. Nunc ut dictum risus. Vestibulum at nisi pellentesque leo cursus malesuada. Nunc in massa diam.\n Etiam cursus, lacus ut aliquam fermentum, justo elit pharetra nisi, eget semper leo ex ut metus. Vivamus arcu orci, varius et pretium vitae, fermentum vitae nisi. Duis in facilisis massa. Quisque fermentum risus rhoncus nisi aliquam tincidunt. Praesent sed pellentesque eros. In tincidunt massa nisi, ut consequat neque feugiat sed. Phasellus varius odio in condimentum accumsan. Vestibulum sit amet malesuada mauris, et pellentesque eros. Etiam sed fermentum ipsum. Duis cursus molestie ligula, hendrerit fermentum sem tristique non. Phasellus viverra sit amet velit ut consequat. Nullam elementum, risus tempus mattis maximus, dui nunc vehicula magna, in faucibus lectus velit in massa. Vivamus mollis mauris vel ipsum aliquam, ac ultrices felis pellentesque.\n Nullam dapibus aliquet dapibus. Pellentesque maximus felis ac neque pretium consectetur. Quisque tincidunt nec magna sit amet convallis. Duis quis placerat mauris, non bibendum purus. Cras vel mattis libero. Donec in elit felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque eu porttitor justo, vel pulvinar dolor. Donec sed tempus enim. Praesent leo ligula, sollicitudin ac nisi a, rhoncus tempor erat. Nam malesuada eros non purus malesuada lacinia. Ut ac aliquet nisi. Etiam dui urna, mattis quis interdum sed, bibendum quis risus. Sed fermentum consectetur tellus, quis tristique metus euismod ac. Mauris pharetra eget massa in suscipit. Etiam posuere, quam in lacinia convallis, quam sem tempor elit, ut commodo ligula lorem eget sem."
    },
    5: {
      id: 5,
      title: "Exam",
      authors: "Federico Bottoni, Nassim Habbash",
      text:
        "Vivamus efficitur sollicitudin ex, quis dapibus dui bibendum vel. Integer bibendum metus iaculis mattis fermentum. Fusce ut tortor odio. Pellentesque nec justo ac ligula pulvinar ultricies. Sed quis quam ac nulla dictum mollis eu id ante. Nullam maximus magna eu convallis blandit. Curabitur tristique scelerisque quam, et iaculis quam ultricies vitae. In neque lacus, volutpat id luctus id, vulputate et ipsum. Proin faucibus, lorem quis luctus tincidunt, massa dolor placerat dolor, sit amet efficitur purus orci quis turpis. Proin fringilla dui quis leo imperdiet, vel laoreet eros volutpat. Mauris in leo ut purus condimentum ullamcorper vitae nec purus. Nunc ut dictum risus. Vestibulum at nisi pellentesque leo cursus malesuada. Nunc in massa diam.\n Etiam cursus, lacus ut aliquam fermentum, justo elit pharetra nisi, eget semper leo ex ut metus. Vivamus arcu orci, varius et pretium vitae, fermentum vitae nisi. Duis in facilisis massa. Quisque fermentum risus rhoncus nisi aliquam tincidunt. Praesent sed pellentesque eros. In tincidunt massa nisi, ut consequat neque feugiat sed. Phasellus varius odio in condimentum accumsan. Vestibulum sit amet malesuada mauris, et pellentesque eros. Etiam sed fermentum ipsum. Duis cursus molestie ligula, hendrerit fermentum sem tristique non. Phasellus viverra sit amet velit ut consequat. Nullam elementum, risus tempus mattis maximus, dui nunc vehicula magna, in faucibus lectus velit in massa. Vivamus mollis mauris vel ipsum aliquam, ac ultrices felis pellentesque.\n Nullam dapibus aliquet dapibus. Pellentesque maximus felis ac neque pretium consectetur. Quisque tincidunt nec magna sit amet convallis. Duis quis placerat mauris, non bibendum purus. Cras vel mattis libero. Donec in elit felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque eu porttitor justo, vel pulvinar dolor. Donec sed tempus enim. Praesent leo ligula, sollicitudin ac nisi a, rhoncus tempor erat. Nam malesuada eros non purus malesuada lacinia. Ut ac aliquet nisi. Etiam dui urna, mattis quis interdum sed, bibendum quis risus. Sed fermentum consectetur tellus, quis tristique metus euismod ac. Mauris pharetra eget massa in suscipit. Etiam posuere, quam in lacinia convallis, quam sem tempor elit, ut commodo ligula lorem eget sem."
    }
  },
  articlesNames: [
    { id: 1, title: "Example" },
    { id: 2, title: "Test" },
    { id: 3, title: "Mock" },
    { id: 4, title: "Example4" },
    { id: 5, title: "Exam" }
  ]
};
